# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
dist: xenial

addons:
  apt:
    packages:
      - libgit2-dev
      - r-base-dev

r_binary_packages:
  - testthat
  - jsonlite
  - git2r
  - ps
  - processx
  - httr
  - dplyr
  - lubridate
  - purrr
  - stringr
  - stringi
  - ggplot2
  - knitr
  - rmarkdown
  - commonmark
  - highlight
  - xml2
  - roxygen2
  - assertthat
  - glue
  - openssl
  - rlang

r_github_packages:
  - r-lib/pkgdown

r:
  - oldrel
  - release
  - devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(run_dont_run = TRUE)'
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_R_VERSION_STRING = release"
