# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_binary_packages:
 - testthat
 - httr
 - dplyr
 - jsonlite

r:
- oldrel
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'
