# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
dist: xenial

addons:
 apt:
  packages:
   - libgit2-dev

r_binary_packages:
 - testthat
 - jsonlite
 - git2r
 - ps
 - processx
 - httr
 - dplyr
 - lubridate
 - purrr
 - stringr
 - ggplot2
 - knitr
 - rmarkdown

r:
- oldrel
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'
